sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      packages:
        - gcc-9
      script:
        - export CC=gcc-9
        - export CXX=g++-9
    
    - os: linux
      dist: bionic
      compiler: clang
      packages:
        - clang-9
  
    - os: windows
      compiler: msvc
    
    - os: osx
      osx_image: xcode11.3
  
script:
  - cmake .
  - cmake --build .