sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

jobs:
  include: 
    - os: linux
      dist: trusty
      compiler: gcc
    
    - os: linux
      dist: trusty
      compiler: clang
  
    - os: windows
      compiler: msvc
    
    #- os: osx
    #  osx_image: xcode10.1
  
script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake .
  - cmake --build . -- -j2