sudo: false
language: cpp

compiler:
  - gcc
  - clang
  - msvc
  - mingw
  
os:
  - linux
  - windows
  - osx

dist: trusty

osx_image: xcode11.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake .
  - cmake --build . -- -j2