language: cpp
os: linux
dist: xenial

cache:
- directories:
  - $HOME/.cache

jobs:
  include:
    ################
    # CLANG BUILDS #
    # ver: 7-9     #
    ################
    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
            # - llvm-toolchain-xenial-7
          # packages:
            # - clang-7
            # - g++-8
            # - lcov
            # - libc++-7-dev
            # - libc++abi-7-dev
            # - libstdc++-7-dev
      # env:
        # - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
        # - CONFIG=Debug

    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
            # - llvm-toolchain-xenial-7
          # packages:
            # - clang-7
            # - g++-8
            # - lcov
            # - libc++-7-dev
            # - libc++abi-7-dev
            # - libstdc++-7-dev
      # env:
        # - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
        # - CONFIG=Release
    
    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
            # - llvm-toolchain-xenial-8
          # packages:
            # - clang-8
            # - g++-8
            # - lcov
            # - libc++-8-dev
            # - libc++abi-8-dev
            # - libstdc++-8-dev
      # env:
        # - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        # - CONFIG=Debug
    
    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
            # - llvm-toolchain-xenial-8
          # packages:
            # - clang-8
            # - g++-8
            # - lcov
            # - libc++-8-dev
            # - libc++abi-8-dev
            # - libstdc++-8-dev
      # env:
        # - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        # - CONFIG=Release
  
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - g++-9
            - lcov
            - libc++-9-dev
            - libc++abi-9-dev
            - libstdc++-9-dev
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
        - CONFIG=Debug
    
    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
            # - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              # key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          # packages:
            # - clang-9
            # - g++-9
            # - lcov
            # - libc++-9-dev
            # - libc++abi-9-dev
            # - libstdc++-9-dev
      # env:
        # - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
        # - CONFIG=Release
    
    ##############
    # GCC BUILDS #
    # ver: 8-9   #
    ############## 
    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
          # packages:
            # - g++-8
            # - lcov
      # env:
        # - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        # - CONFIG=Debug

    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
          # packages:
            # - g++-8
            # - lcov
      # env:
        # - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        # - CONFIG=Release

    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
          # packages:
            # - g++-9
            # - lcov
      # env:
        # - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        # - CONFIG=Debug
    
    # - addons:
        # apt:
          # sources:
            # - ubuntu-toolchain-r-test
          # packages:
            # - g++-9
            # - lcov
      # env:
        # - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        # - CONFIG=Release
  
before_install:
  - eval "${MATRIX_EVAL}"

install:
  - mkdir -p $HOME/.cache
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
      LCOV_URL="https://github.com/linux-test-project/lcov/releases/download/v1.14/lcov-1.14.tar.gz"
      mkdir lcov && travis_retry wget --no-check-certificate -O - ${LCOV_URL} | tar --strip-components=1 -xz -C lcov
      cd lcov
      make install
      export PATH=${DEPS_DIR}/lcov/bin:${PATH}
  - cd ${TRAVIS_BUILD_DIR}
  
script:
  - mkdir -p build && cd build
  - cmake --version
  - cmake -DBUILD_TESTING=ON -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=${CONFIG} ..
  - cmake --build . --config ${CONFIG} -- -j $(nproc)
  - ctest --verbose --output-on-failure -C ${CONFIG} -j $(nproc)

after_success:
  - lcov --version
  - lcov --directory . --capture --output-file coverage.info --gcov-tool gcov-8
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"