sudo: false
language: cpp


matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
      script:
        - export CC=gcc-9
        - export CXX=g++-9
        - cmake .
        - cmake --build . 
    
    - os: linux
      dist: bionic
      compiler: clang
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
      script:
        - export CC=gcc-9
        - export CXX=g++-9
        - cmake .
        - cmake --build . 
  
#    - os: windows
#      compiler: msvc
    
#    - os: osx
#      osx_image: xcode11.3
  
script: