sudo: false
language: cpp

matrix:
  include:
    ################
    # CLANG BUILDS #
    ################
    - os: linux
      compiler: clang
      dist:
        - precise
        - trusty
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    - os: linux
      compiler: clang
      dist:
        - precise
        - trusty
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

    - os: linux
      compiler: clang
      dist:
        - precise
        - trusty
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    - os: linux
      compiler: clang
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: linux
      compiler: clang
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      compiler: clang
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        # works on Trusty
  
    - os: linux
      compiler: clang
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    
    - os: linux
      compiler: clang
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"
    
    ##############
    # GCC BUILDS #
    ##############    
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
  
    #- os: windows
    
    #- os: osx
    #  osx_image: xcode10.1
  
before_install:
    - eval "${MATRIX_EVAL}"
  
script:
  - cmake .
  - cmake --build .