platform: 
  - x64
  
image:
  - Visual Studio 2017
  - Visual Studio 2019
    
build_script:
- cmd: cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_TESTING=ON -DCODE_COVERAGE=OFF -DBUILD_SHARED_LIBS=0 . 

# Debug Build
- cmd: cmake --build . --clean-first --config Debug -- -j2
- cmd: ctest --verbose --output-on-failure -C Debug -j2

# Release Build
- cmd: cmake --build . --clean-first --config Release -- -j2
- cmd: ctest --verbose --output-on-failure -C Release -j2