platform: 
  - x64
  
image:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug
  - Release
    
build_script:
- cmd: cmake -D CMAKE_GENERATOR_PLATFORM=x64 UNIT_TESTS:BOOL=TRUE ENABLE_COVERAGE:BOOL=FALSE BUILD_SHARED_LIBS=0 . 
- cmd: cmake --build . --config %configuration% 
- cmd: ctest --verbose -C %configuration%