image:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug
  - Release  
    
build_script:
- cmd: cmake -D UNIT_TESTS:BOOL=TRUE -H. -B./build -DBUILD_SHARED_LIBS=0
- cmd: ctest --verbose