environment:
  platform: x64
  
  matrix:
    - image: Visual Studio 2017
      configuration: Debug
	  config: Debug
	  
	- image: Visual Studio 2017
      configuration: Release
	  config: Release
	  
	- image: Visual Studio 2019
      configuration: Debug
	  config: Debug
	  
	- image: Visual Studio 2019
      configuration: Release
	  config: Release
    
build_script:
- cmd: cmake -C config -D CMAKE_GENERATOR_PLATFORM=x64 UNIT_TESTS:BOOL=TRUE ENABLE_COVERAGE:BOOL=FALSE BUILD_SHARED_LIBS=0 . 
- cmd: cmake --build .
- cmd: ctest --verbose