version: 2.1
jobs:
  build:
    docker:
      - image: clang:latest
    steps:
      - checkout
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Running CMake
          command: |
            cmake -DBUILD_TESTING=ON -DCODE_COVERAGE=OFF -DSTATIC_ANALYSIS=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_CLANG_TIDY=clang-tidy . || exit 1
            cmake --build . --clean-first -- -j $(nproc) || exit 1
            ctest --output-on-failure --quiet -j $(nproc) -C Debug . || exit 1